/**
 * Automated Supabase PostgreSQL Integration Test Suite for DrawRealm
 * Tests:
 * 1. New Player Creation in Supabase
 * 2. Returning Player State Restoration (XP, level, powers, stats)
 * 3. Evolution Power Unlock & Cross-Session Persistence
 * 4. Multiplayer Match History & Player Stats Update
 * 5. Duplicate Prevention (Idempotent profile, achievement, match writes)
 */

const { io } = require("socket.io-client");
const http = require("http");
const assert = require("assert");
const supabaseService = require("../server/db/supabaseClient");

const SERVER_URL = "http://localhost:3001";

function wait(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function waitFor(fn, timeoutMs = 12000, intervalMs = 50) {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    const check = () => {
      try {
        const res = fn();
        if (res) return resolve(res);
      } catch (e) {}
      if (Date.now() - start > timeoutMs) {
        return reject(new Error(`Timeout waiting for condition after ${timeoutMs}ms`));
      }
      setTimeout(check, intervalMs);
    };
    check();
  });
}

function createClient(name) {
  const socket = io(SERVER_URL, {
    transports: ["websocket"],
    forceNew: true,
    reconnection: false
  });

  const state = {
    socket,
    name,
    id: null,
    roomId: null,
    reconnectToken: null,
    roomInit: null,
    gameState: null,
    evolutionState: null,
    rawPackets: [],
    chatMessages: []
  };

  socket.on("drawrealm:session", (sess) => {
    state.reconnectToken = sess.token;
    state.roomId = sess.roomId;
    state.id = sess.playerId;
  });

  socket.on("evolution:state", (evo) => {
    state.evolutionState = evo;
  });

  socket.on("data", (packet) => {
    if (!packet) return;
    state.rawPackets.push(packet);
    if (packet.id === 10) { // ROOM_INIT
      state.roomInit = packet.data;
      state.id = packet.data.me;
      state.roomId = packet.data.id;
      state.reconnectToken = packet.data.reconnectToken;
      if (packet.data.state) state.gameState = packet.data.state;
    } else if (packet.id === 11) { // STATE
      state.gameState = packet.data;
    } else if (packet.id === 30) { // CHAT
      state.chatMessages.push(packet.data);
    }
  });

  return state;
}

async function run() {
  console.log("==================================================");
  console.log("    DRAWREALM SUPABASE POSTGRESQL VERIFICATION    ");
  console.log("==================================================");

  assert(supabaseService.isConfigured, "Supabase client must be configured with URL and Service Role Key");

  // -------------------------------------------------------------------------
  // TEST 1: New Player Creation in Supabase
  // -------------------------------------------------------------------------
  console.log("\n[TEST 1] Testing New Player Creation in Supabase...");
  const timestamp = String(Date.now()).slice(-6);
  const testUsernameA = `SupaA_${timestamp}`;

  const playerA = await supabaseService.getOrCreatePlayer(testUsernameA, "Player Alpha");
  assert(playerA, "getOrCreatePlayer must return player object");
  assert(playerA.id, "Player must have a UUID generated by Supabase");
  assert.strictEqual(playerA.username, testUsernameA, "Username must match");
  assert.strictEqual(playerA.evolution.xp, 0, "Default XP must be 0");
  assert.strictEqual(playerA.evolution.level, 0, "Default level must be 0");

  // Verify directly from Supabase REST API
  const { data: profileRows } = await supabaseService.client
    .from("profiles")
    .select("*")
    .eq("id", playerA.id);
  assert(profileRows && profileRows.length === 1, "Profile must exist in Supabase profiles table");

  const { data: statsRows } = await supabaseService.client
    .from("player_stats")
    .select("*")
    .eq("player_id", playerA.id);
  assert(statsRows && statsRows.length === 1, "Stats must exist in Supabase player_stats table");

  const { data: evoRows } = await supabaseService.client
    .from("evolution_profiles")
    .select("*")
    .eq("player_id", playerA.id);
  assert(evoRows && evoRows.length === 1, "Evolution profile must exist in Supabase evolution_profiles table");

  console.log(`  ✓ New player created in Supabase (UUID: ${playerA.id})`);
  console.log(`  ✓ Verified rows in profiles, player_stats, and evolution_profiles`);

  // -------------------------------------------------------------------------
  // TEST 2: Evolution State & Power Unlock Persistence
  // -------------------------------------------------------------------------
  console.log("\n[TEST 2] Testing Evolution State & Power Unlock Persistence...");
  // Update Evolution XP, level, and power unlock
  await supabaseService.saveEvolutionState(playerA.id, {
    xp: 500,
    level: 3,
    branch: "creator",
    ultimatePower: "chrono_shift",
    unlockedPowers: ["score_surge", "point_bomb", "chrono_shift"],
    equippedPowers: ["score_surge", "point_bomb"]
  });

  // Verify in Supabase
  const { data: updatedEvo } = await supabaseService.client
    .from("evolution_profiles")
    .select("*")
    .eq("player_id", playerA.id)
    .single();

  assert.strictEqual(updatedEvo.xp, 500, "Supabase XP must be 500");
  assert.strictEqual(updatedEvo.level, 3, "Supabase level must be 3");
  assert.strictEqual(updatedEvo.ultimate_power, "chrono_shift", "Supabase ultimate power must be chrono_shift");
  console.log(`  ✓ Evolution state persisted in Supabase: XP=${updatedEvo.xp}, Level=${updatedEvo.level}, Ultimate=${updatedEvo.ultimate_power}`);

  // -------------------------------------------------------------------------
  // TEST 3: Returning Player Retrieval (No Progress Reset)
  // -------------------------------------------------------------------------
  console.log("\n[TEST 3] Testing Returning Player Retrieval across sessions...");
  // Simulate reconnecting or logging in from another device
  const returningPlayerA = await supabaseService.getOrCreatePlayer(testUsernameA);
  assert.strictEqual(returningPlayerA.id, playerA.id, "Must resolve to identical player UUID");
  assert.strictEqual(returningPlayerA.evolution.xp, 500, "Returning player must keep 500 XP");
  assert.strictEqual(returningPlayerA.evolution.level, 3, "Returning player must keep Level 3");
  assert.strictEqual(returningPlayerA.evolution.ultimatePower, "chrono_shift", "Returning player must keep ultimate power");
  console.log(`  ✓ Returning player cleanly resolved: Same UUID, exactly 500 XP, Level 3, and powers preserved!`);

  // -------------------------------------------------------------------------
  // TEST 4: Duplicate Prevention (Idempotent Profiles & Achievements)
  // -------------------------------------------------------------------------
  console.log("\n[TEST 4] Testing Duplicate Prevention & Idempotency...");
  // 1. Duplicate profile creation attempt
  const dupAttempt = await supabaseService.getOrCreatePlayer(testUsernameA);
  assert.strictEqual(dupAttempt.id, playerA.id, "Must not create duplicate profile");

  const { data: allMatching } = await supabaseService.client
    .from("profiles")
    .select("id")
    .eq("username", testUsernameA);
  assert.strictEqual(allMatching.length, 1, "Profiles table must contain exactly 1 row for username");
  console.log("  ✓ Idempotent player creation: 0 duplicate profiles created");

  // 2. Duplicate achievement unlock attempt
  await supabaseService.unlockAchievement(playerA.id, "first_evolution");
  await supabaseService.unlockAchievement(playerA.id, "first_evolution"); // Duplicate call

  if (supabaseService.tableSupport.achievements) {
    const { data: achRows } = await supabaseService.client
      .from("achievements")
      .select("*")
      .eq("player_id", playerA.id)
      .eq("achievement_id", "first_evolution");
    if (achRows) {
      assert.strictEqual(achRows.length, 1, "Achievements table must not contain duplicate achievement");
      console.log("  ✓ Idempotent achievement unlock: exactly 1 achievement row exists");
    }
  }

  // -------------------------------------------------------------------------
  // TEST 5: Multiplayer Match History & Player Stats Update
  // -------------------------------------------------------------------------
  console.log("\n[TEST 5] Testing Match History Recording & Player Stats Aggregation...");
  const testUsernameB = `SupaB_${timestamp}`;
  const testUsernameC = `SupaC_${timestamp}`;

  const playerB = await supabaseService.getOrCreatePlayer(testUsernameB, "Player Beta");
  const playerC = await supabaseService.getOrCreatePlayer(testUsernameC, "Player Gamma");

  const matchData = {
    roomId: "test_room",
    mode: "evolution",
    winnerId: playerA.id,
    players: [
      { playerId: playerA.id, score: 750, xpEarned: 150, position: 1, correctGuesses: 3, roundsPlayed: 2, streak: 3 },
      { playerId: playerB.id, score: 450, xpEarned: 90, position: 2, correctGuesses: 2, roundsPlayed: 2, streak: 1 },
      { playerId: playerC.id, score: 200, xpEarned: 40, position: 3, correctGuesses: 1, roundsPlayed: 2, streak: 0 }
    ]
  };

  await supabaseService.recordMatch(matchData);
  console.log("  ✓ Match results recorded through Supabase service");

  // Verify Player A stats were incremented
  const { data: updatedStatsA } = await supabaseService.client
    .from("player_stats")
    .select("*")
    .eq("player_id", playerA.id)
    .single();

  assert.strictEqual(updatedStatsA.games_played, 1, "Player A games_played must be 1");
  assert.strictEqual(updatedStatsA.games_won, 1, "Player A games_won must be 1");
  assert.strictEqual(updatedStatsA.best_score, 750, "Player A best_score must be 750");
  assert.strictEqual(updatedStatsA.correct_guesses, 3, "Player A correct_guesses must be 3");
  assert.strictEqual(updatedStatsA.highest_streak, 3, "Player A highest_streak must be 3");
  console.log(`  ✓ Player stats atomically updated: Games=${updatedStatsA.games_played}, Won=${updatedStatsA.games_won}, BestScore=${updatedStatsA.best_score}, Guesses=${updatedStatsA.correct_guesses}`);

  // Verify Player B stats
  const { data: updatedStatsB } = await supabaseService.client
    .from("player_stats")
    .select("*")
    .eq("player_id", playerB.id)
    .single();

  assert.strictEqual(updatedStatsB.games_played, 1, "Player B games_played must be 1");
  assert.strictEqual(updatedStatsB.games_won, 0, "Player B games_won must be 0");
  assert.strictEqual(updatedStatsB.best_score, 450, "Player B best_score must be 450");
  console.log(`  ✓ Participant stats updated: Games=${updatedStatsB.games_played}, Won=${updatedStatsB.games_won}, BestScore=${updatedStatsB.best_score}`);

  // -------------------------------------------------------------------------
  // TEST 6: Real-Time WebSocket Game Sync with Supabase Profile
  // -------------------------------------------------------------------------
  console.log("\n[TEST 6] Testing Real-Time WebSocket Integration with Supabase...");
  const clientA = createClient(testUsernameA);
  await waitFor(() => clientA.socket.connected);

  clientA.socket.emit("login", {
    create: 1,
    name: testUsernameA,
    lang: "en",
    mode: 6
  });

  await waitFor(() => clientA.roomInit && clientA.roomId);
  console.log(`  ✓ Client connected to room ${clientA.roomId}`);

  // Wait for background Supabase profile resolution & evolution sync
  await waitFor(() => clientA.evolutionState && clientA.evolutionState.xp >= 500, 5000);
  assert.strictEqual(clientA.evolutionState.level, 3, "In-game evolution level must match Supabase level 3");
  console.log(`  ✓ In-game evolution state seamlessly loaded from Supabase: XP=${clientA.evolutionState.xp}, Level=${clientA.evolutionState.level}`);

  // Clean up socket
  clientA.socket.disconnect();

  // -------------------------------------------------------------------------
  // CLEANUP TEST USERS
  // -------------------------------------------------------------------------
  console.log("\nCleaning up test artifacts from Supabase...");
  await supabaseService.client.from("profiles").delete().in("id", [playerA.id, playerB.id, playerC.id]);
  console.log("  ✓ Test profiles safely removed from Supabase");

  console.log("\n==================================================");
  console.log("   ALL SUPABASE INTEGRATION TESTS PASSED!         ");
  console.log("==================================================");
  process.exit(0);
}

run().catch((err) => {
  console.error("\n❌ SUPABASE TEST SUITE FAILED:", err);
  process.exit(1);
});
